[package]
name = "oxidepdf-web"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"
rust-version.workspace = true
description = "Web front end for OxidePDF."

[[bin]]
name = "oxidepdf-web"
path = "src/main.rs"

[dependencies]
axum = { workspace = true }
clap = { workspace = true }
tower-http = { workspace = true }
uuid = { workspace = true }
oxidepdf-core = { workspace = true }
schemars = { workspace = true }
tokio = { workspace = true, features = ["net", "fs", "rt"] }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
