//! Integration tests for the `annotations` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn annotation_inspection_reports_malformed_annotation_array() {
    let err = inspect_pdf_annotations(
        &pdf_with_malformed_annotation_array(),
        &AnnotationInspectOptions::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::ParsePdf));
}

#[test]
fn annotations_add_list_delete_and_interactive_removal_are_selective() {
    let pdf = empty_page_pdf();
    let annotated = edit_pdf_annotations(
        &pdf,
        &AnnotationEditOptions {
            action: AnnotationEditAction::AddText,
            page: Some(1),
            id: Some("review-note".to_owned()),
            text: Some("Review this page".to_owned()),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = inspect_pdf_annotations(&annotated.bytes, &AnnotationInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert_eq!(report["annotations"][0]["id"], "review-note");
    assert_eq!(report["annotations"][0]["text"], "Review this page");

    let removed = remove_pdf_interactive_elements(
        &annotated.bytes,
        &InteractiveRemovalOptions {
            annotations: true,
            forms: false,
            actions: false,
            javascript: false,
            embedded_files: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = inspect_pdf_annotations(&removed.bytes, &AnnotationInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert!(report["annotations"].as_array().unwrap().is_empty());
}
