//! Integration tests for the `attachments` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn attachments_add_list_extract_and_delete() {
    let pdf = empty_page_pdf();
    let edited = edit_pdf_attachment_artifacts(
        &[Artifact::pdf(&pdf), Artifact::bytes(b"attachment bytes")],
        &AttachmentEditOptions {
            action: AttachmentEditAction::Add,
            name: Some("note.txt".to_owned()),
            description: Some("Review note".to_owned()),
        },
        &ResourceLimits::default(),
    )
    .unwrap();

    let report = inspect_pdf_attachments(&edited.bytes, &AttachmentInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert_eq!(report["attachments"][0]["name"], "note.txt");
    assert_eq!(report["attachments"][0]["description"], "Review note");
    assert_eq!(report["attachments"][0]["size"], 16);

    let extracted =
        extract_pdf_attachment(&edited.bytes, "note.txt", &ResourceLimits::default()).unwrap();
    assert_eq!(extracted.bytes.as_slice(), b"attachment bytes");

    let deleted = edit_pdf_attachment_artifacts(
        &[Artifact::pdf(&edited.bytes)],
        &AttachmentEditOptions {
            action: AttachmentEditAction::Delete,
            name: Some("note.txt".to_owned()),
            description: None,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = inspect_pdf_attachments(&deleted.bytes, &AttachmentInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert!(report["attachments"].as_array().unwrap().is_empty());
}

#[test]
fn attachment_inspection_reports_malformed_names_tree() {
    let err = inspect_pdf_attachments(
        &pdf_with_malformed_names_tree(),
        &AttachmentInspectOptions::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::ParsePdf));
}
