//! Integration tests for the `compression` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn compress_pdf_lossless_prunes_and_preserves_pages() {
    let pdf = pdf_with_unreferenced_stream_object();
    let before = lopdf::Document::load_mem(&pdf).unwrap();
    assert_eq!(before.get_pages().len(), 1);
    assert_eq!(before.objects.len(), 4);

    let compressed = compress_pdf(
        &pdf,
        &CompressionOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap();
    let after = lopdf::Document::load_mem(&compressed.bytes).unwrap();

    assert_eq!(after.get_pages().len(), 1);
    assert_eq!(after.objects.len(), 3);
    assert!(compressed.bytes.starts_with(b"%PDF-"));
}

#[test]
fn compress_pdf_recompresses_plain_content_streams() {
    let pdf = pdf_with_large_plain_content_stream();
    let before = lopdf::Document::load_mem(&pdf).unwrap();
    let before_stream = first_page_content_stream(&before);
    assert!(!before_stream.dict.has(b"Filter"));

    let compressed = compress_pdf(
        &pdf,
        &CompressionOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap();
    let after = lopdf::Document::load_mem(&compressed.bytes).unwrap();
    let after_stream = first_page_content_stream(&after);

    assert_eq!(
        after_stream.dict.get(b"Filter").unwrap().as_name().unwrap(),
        b"FlateDecode"
    );
    assert_eq!(
        after_stream.get_plain_content().unwrap(),
        before_stream.content
    );
}

#[test]
fn compress_pdf_merges_duplicate_image_resources_without_reencoding() {
    let pdf = pdf_with_duplicate_image_resources();
    let before = lopdf::Document::load_mem(&pdf).unwrap();
    let (left_before, right_before) = duplicate_image_resource_ids(&before);
    assert_ne!(left_before, right_before);

    let compressed = compress_pdf(
        &pdf,
        &CompressionOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap();
    let after = lopdf::Document::load_mem(&compressed.bytes).unwrap();
    let (left_after, right_after) = duplicate_image_resource_ids(&after);

    assert_eq!(after.get_pages().len(), 1);
    assert_eq!(left_after, right_after);
    let image_stream = after.get_object(left_after).unwrap().as_stream().unwrap();
    assert_eq!(image_stream.content, b"rgbpixel!");
    assert!(!image_stream.dict.has(b"Filter"));
}

#[test]
fn compress_pdf_lossless_keeps_jpeg_image_streams() {
    let image = include_bytes!("../../../tests/test.jpg");
    let pdf = image_artifacts_to_pdf(
        &[Artifact::image(image)],
        &ImageToPdfOptions {
            layout: Some("original_size".to_owned()),
        },
        &ResourceLimits::default(),
    )
    .unwrap();

    let compressed = compress_pdf(
        &pdf.bytes,
        &CompressionOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&compressed.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 1);
}

#[test]
fn compress_pdf_rejects_lossless_image_options() {
    let err = compress_pdf(
        &empty_page_pdf(),
        &CompressionOptions {
            mode: CompressionMode::Lossless,
            images: Some(CompressionImageOptions {
                quality: Some(80),
                max_width: None,
                max_height: None,
                format: None,
            }),
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::InvalidInput {
            reason: "lossless compression does not accept image resampling or reencoding options"
                .to_owned()
        }
    );
}

#[test]
fn compress_pdf_rejects_lossy_without_explicit_image_options() {
    let err = compress_pdf(
        &empty_page_pdf(),
        &CompressionOptions {
            mode: CompressionMode::Lossy,
            images: None,
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::InvalidInput {
            reason: "lossy compression requires explicit image options".to_owned()
        }
    );
}

#[test]
fn compress_pdf_reencodes_images_when_lossy_options_are_explicit() {
    let compressed = compress_pdf(
        &pdf_with_duplicate_image_resources(),
        &CompressionOptions {
            mode: CompressionMode::Lossy,
            images: Some(CompressionImageOptions {
                quality: Some(80),
                max_width: Some(1),
                max_height: None,
                format: Some(CompressionImageFormat::Jpeg),
            }),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&compressed.bytes).unwrap();
    let (left, right) = duplicate_image_resource_ids(&document);
    assert_eq!(left, right);
    let image_stream = document.get_object(left).unwrap().as_stream().unwrap();
    assert_eq!(
        image_stream.dict.get(b"Filter").unwrap().as_name().unwrap(),
        b"DCTDecode"
    );
    assert!(image_stream.content.starts_with(&[0xFF, 0xD8]));
}

#[test]
fn compress_pdf_returns_unsupported_for_non_jpeg_lossy_target() {
    let err = compress_pdf(
        &pdf_with_duplicate_image_resources(),
        &CompressionOptions {
            mode: CompressionMode::Lossy,
            images: Some(CompressionImageOptions {
                quality: Some(80),
                max_width: None,
                max_height: None,
                format: Some(CompressionImageFormat::Png),
            }),
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::UnsupportedPdfFeature {
            feature: "lossy image target formats other than jpeg".to_owned()
        }
    );
}

#[test]
fn compress_pdf_rejects_unsupported_stream_filter() {
    let err = compress_pdf(
        &pdf_with_unsupported_filtered_stream(),
        &CompressionOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::UnsupportedPdfFeature {
            feature: "stream filter 'DCTDecode'".to_owned()
        }
    );
}
