//! Integration tests for the `compare` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn compare_identical_pdf_report_is_equal() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let artifact =
        compare_pdf_report(pdf, pdf, &CompareOptions::default(), &Default::default()).unwrap();
    let report: CompareReport = serde_json::from_str(&artifact.text).unwrap();

    assert!(report.equal);
    assert!(report.differences.is_empty());
    assert_eq!(report.left.page_count, 3);
    assert_eq!(report.left, report.right);
}

#[test]
fn compare_report_locates_metadata_difference() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let changed = edit_pdf_metadata(
        pdf,
        &MetadataEditOptions {
            action: MetadataEditAction::Set,
            entries: metadata_entries([("title", "Changed Title")]),
            keys: Vec::new(),
        },
        &Default::default(),
    )
    .unwrap();

    let artifact = compare_pdf_report(
        pdf,
        &changed.bytes,
        &CompareOptions::default(),
        &Default::default(),
    )
    .unwrap();
    let report: CompareReport = serde_json::from_str(&artifact.text).unwrap();

    assert!(!report.equal);
    assert!(report.differences.iter().any(|difference| difference.code
        == CompareDifferenceCode::MetadataMismatch
        && difference.path == "metadata"));
}

#[test]
fn compare_report_locates_page_size_difference() {
    let left = empty_page_pdf();
    let right = pdf_with_media_box(300, 400);

    let artifact = compare_pdf_report(
        &left,
        &right,
        &CompareOptions {
            include_text: false,
            ..CompareOptions::default()
        },
        &Default::default(),
    )
    .unwrap();
    let report: CompareReport = serde_json::from_str(&artifact.text).unwrap();

    assert!(!report.equal);
    assert!(report.differences.iter().any(|difference| difference.code
        == CompareDifferenceCode::PageSizeMismatch
        && difference.path == "pages[1].size"));
}

#[test]
fn compare_report_locates_text_difference() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let changed = watermark_pdf_artifacts(
        &[Artifact::pdf(pdf)],
        &WatermarkOptions {
            kind: WatermarkKind::Text,
            text: Some("VISIBLE TEXT DIFFERENCE".to_owned()),
            font: Some("Helvetica".to_owned()),
            font_path: None,
            font_size: Some(24.0),
            opacity: Some(1.0),
            rotation: Some(0.0),
            position: Some("center".to_owned()),
            pages: Some("1".to_owned()),
            scale: None,
            rasterize: false,
        },
        &Default::default(),
    )
    .unwrap();

    let artifact = compare_pdf_report(
        pdf,
        &changed.bytes,
        &CompareOptions::default(),
        &Default::default(),
    )
    .unwrap();
    let report: CompareReport = serde_json::from_str(&artifact.text).unwrap();

    assert!(!report.equal);
    assert!(report.differences.iter().any(|difference| difference.code
        == CompareDifferenceCode::TextMismatch
        && difference.path == "text"));
}

#[test]
fn compare_report_makes_page_count_mismatch_explicit() {
    let left = empty_page_pdf();
    let right = pdf_with_blank_and_marked_page();

    let artifact = compare_pdf_report(
        &left,
        &right,
        &CompareOptions {
            include_text: false,
            ..CompareOptions::default()
        },
        &Default::default(),
    )
    .unwrap();
    let report: CompareReport = serde_json::from_str(&artifact.text).unwrap();

    assert!(!report.equal);
    assert!(report.differences.iter().any(|difference| difference.code
        == CompareDifferenceCode::PageCountMismatch
        && difference.path == "pages.count"
        && difference.left == serde_json::json!(1)
        && difference.right == serde_json::json!(2)));
}

#[test]
fn compare_workflow_produces_text_report() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [
                { "id": "left", "path": "left.pdf" },
                { "id": "right", "path": "right.pdf" }
              ],
              "tasks": [
                {
                  "id": "compare",
                  "op": { "pdf_compare": { "report": {} } },
                  "inputs": ["left", "right"]
                }
              ],
              "outputs": [{ "id": "final", "from": "compare", "path": "report.json" }]
            }
            "#,
    );
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("left"), Artifact::pdf(pdf));
    store.insert(artifact_ref("right"), Artifact::pdf(pdf));
    let runner = PdfOperatorRunner::default();

    let result = execute_workflow(&workflow, store, &runner).unwrap();

    match result.store.get(&artifact_ref("compare")).unwrap() {
        Artifact::Text(artifact) => {
            let report: CompareReport = serde_json::from_str(&artifact.text).unwrap();
            assert!(report.equal);
        }
        other => panic!("expected text compare report, got {other:?}"),
    }
}

#[test]
fn compare_visual_diff_outputs_non_empty_png() {
    let left = empty_page_pdf();
    let right = pdf_with_rgb_fill_content();

    let artifact = compare_pdf_visual_diff(
        &left,
        &right,
        &VisualDiffOptions {
            page: 1,
            scale: Some(1.0),
        },
        &Default::default(),
    )
    .unwrap();
    let image = image::load_from_memory(&artifact.bytes).unwrap().to_rgba8();

    assert!(!artifact.bytes.is_empty());
    assert!(image.width() > 0);
    assert!(image.height() > 0);
    assert!(image.pixels().any(|pixel| pixel.0 == [220, 38, 38, 255]));
}

#[test]
fn compare_visual_diff_marks_page_size_difference() {
    let left = pdf_with_media_box(100, 100);
    let right = pdf_with_media_box(120, 100);

    let artifact = compare_pdf_visual_diff(
        &left,
        &right,
        &VisualDiffOptions {
            page: 1,
            scale: Some(1.0),
        },
        &Default::default(),
    )
    .unwrap();
    let image = image::load_from_memory(&artifact.bytes).unwrap().to_rgba8();

    assert!(image.pixels().any(|pixel| pixel.0 == [220, 38, 38, 255]));
}
