//! Integration tests for the `forms` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn form_inspection_reports_malformed_acroform() {
    let err = inspect_pdf_forms(
        &pdf_with_malformed_acroform(),
        &FormInspectOptions::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::ParsePdf));
}

#[test]
fn forms_fill_unlock_and_remove_without_appearance_fallback() {
    let pdf = pdf_with_text_form_field(true);
    let filled = fill_pdf_form(
        &pdf,
        &FormFillOptions {
            fields: vec![FormFieldValue {
                name: "customer".to_owned(),
                value: "Ada".to_owned(),
            }],
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = inspect_pdf_forms(&filled.bytes, &FormInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert_eq!(report["fields"][0]["name"], "customer");
    assert_eq!(report["fields"][0]["value"], "Ada");
    assert_eq!(report["fields"][0]["readonly"], true);

    let unlocked = unlock_pdf_form_readonly(&filled.bytes, &ResourceLimits::default()).unwrap();
    let report = inspect_pdf_forms(&unlocked.bytes, &FormInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert_eq!(report["fields"][0]["readonly"], false);

    let removed = remove_pdf_forms(&unlocked.bytes, &ResourceLimits::default()).unwrap();
    let report = inspect_pdf_forms(&removed.bytes, &FormInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert!(report["fields"].as_array().unwrap().is_empty());

    let xfa_err = fill_pdf_form(
        &pdf_with_xfa_form(),
        &FormFillOptions {
            fields: vec![FormFieldValue {
                name: "customer".to_owned(),
                value: "Ada".to_owned(),
            }],
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();
    assert!(matches!(xfa_err, OxideError::UnsupportedPdfFeature { .. }));
    assert!(xfa_err.to_string().contains("XFA"));
}
