//! Integration tests for the `interactive` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn interactive_removal_reports_malformed_names_tree() {
    let err = remove_pdf_interactive_elements(
        &pdf_with_malformed_names_tree(),
        &InteractiveRemovalOptions {
            annotations: false,
            forms: false,
            actions: false,
            javascript: true,
            embedded_files: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::ParsePdf));
}
