//! Integration tests for the `metadata` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn metadata_set_delete_validate_and_report_are_deterministic() {
    let pdf = empty_page_pdf();
    let edited = edit_pdf_metadata(
        &pdf,
        &MetadataEditOptions {
            action: MetadataEditAction::Set,
            entries: metadata_entries([("title", "Quarterly Report"), ("author", "OxidePDF")]),
            keys: Vec::new(),
        },
        &ResourceLimits::default(),
    )
    .unwrap();

    let report = inspect_pdf_metadata(&edited.bytes, &MetadataInspectOptions::default()).unwrap();
    let report: serde_json::Value = serde_json::from_str(&report.text).unwrap();
    assert_eq!(report["valid"], true);
    assert_eq!(report["entries"]["title"], "Quarterly Report");
    assert_eq!(report["entries"]["author"], "OxidePDF");

    let deleted = edit_pdf_metadata(
        &edited.bytes,
        &MetadataEditOptions {
            action: MetadataEditAction::Delete,
            entries: Vec::new(),
            keys: vec!["author".to_owned()],
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let deleted_again = edit_pdf_metadata(
        &deleted.bytes,
        &MetadataEditOptions {
            action: MetadataEditAction::Delete,
            entries: Vec::new(),
            keys: vec!["author".to_owned()],
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    assert_eq!(
        inspect_pdf_metadata(&deleted.bytes, &MetadataInspectOptions::default())
            .unwrap()
            .text,
        inspect_pdf_metadata(&deleted_again.bytes, &MetadataInspectOptions::default())
            .unwrap()
            .text
    );
}

#[test]
fn metadata_inspection_reports_name_valued_trapped_entry() {
    let report = inspect_pdf_metadata(
        &pdf_with_named_info_value(),
        &MetadataInspectOptions::default(),
    )
    .unwrap();
    let report: serde_json::Value = serde_json::from_str(&report.text).unwrap();
    assert_eq!(report["entries"]["title"], "Sample");
    assert_eq!(report["entries"]["trapped"], "True");
}
