//! Integration tests for the `outlines` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn outline_set_get_and_delete_are_stable() {
    let pdf = empty_page_pdf();
    let outline = OutlineTree {
        items: vec![OutlineItem {
            title: "Chapter 1".to_owned(),
            page: 1,
            children: vec![OutlineItem {
                title: "Section 1.1".to_owned(),
                page: 1,
                children: Vec::new(),
            }],
        }],
    };

    let edited = edit_pdf_outline(
        &pdf,
        &OutlineEditOptions {
            action: OutlineEditAction::Set,
            tree: Some(outline.clone()),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = inspect_pdf_outline(&edited.bytes, &OutlineInspectOptions::default()).unwrap();
    let report: OutlineTree = serde_json::from_str(&report.text).unwrap();
    assert_eq!(report, outline);

    let deleted = edit_pdf_outline(
        &edited.bytes,
        &OutlineEditOptions {
            action: OutlineEditAction::Delete,
            tree: None,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = inspect_pdf_outline(&deleted.bytes, &OutlineInspectOptions::default()).unwrap();
    let report: OutlineTree = serde_json::from_str(&report.text).unwrap();
    assert!(report.items.is_empty());
}

#[test]
fn outline_inspection_rejects_unsupported_destinations_without_defaulting_page() {
    let err = inspect_pdf_outline(
        &pdf_with_named_outline_destination(),
        &OutlineInspectOptions::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::UnsupportedPdfFeature { .. }));
    assert!(err.to_string().contains("outline"));
}

#[test]
fn outline_inspection_rejects_cyclic_siblings_without_hanging() {
    let err = inspect_pdf_outline(
        &pdf_with_cyclic_outline(),
        &OutlineInspectOptions::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::ParsePdf));
}
