//! Integration tests for the `overlay` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn overlay_pdf_page_and_signature_appearance_are_visual_only() {
    let pdf = empty_page_pdf();
    let overlay = include_bytes!("../../../tests/test.pdf");
    let overlaid = overlay_pdf_artifacts(
        &[Artifact::pdf(&pdf), Artifact::pdf(overlay)],
        &OverlayOptions {
            kind: OverlayKind::PdfPage,
            text: None,
            font: None,
            font_path: None,
            font_size: None,
            opacity: Some(1.0),
            rotation: None,
            position: Some("center".to_owned()),
            pages: Some("1".to_owned()),
            scale: Some(0.5),
            rasterize: false,
            source_page: Some(1),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&overlaid.bytes).unwrap();
    assert!(page_resources(&document, 1).has(b"XObject"));
    assert!(page_content_contains_operator(&document, 1, "Do"));

    let appearance = overlay_pdf_artifacts(
        &[Artifact::pdf(&pdf)],
        &OverlayOptions {
            kind: OverlayKind::SignatureAppearance,
            text: Some("Ada Lovelace".to_owned()),
            font: Some("Helvetica".to_owned()),
            font_path: None,
            font_size: Some(24.0),
            opacity: Some(1.0),
            rotation: None,
            position: Some("bottom_right".to_owned()),
            pages: Some("1".to_owned()),
            scale: None,
            rasterize: false,
            source_page: None,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let trust_anchors = write_test_trust_anchors("signature_appearance_report");
    let report = verify_pdf_signatures(
        &appearance.bytes,
        &SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(trust_anchors),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report: serde_json::Value = serde_json::from_str(&report.text).unwrap();
    assert!(report["signatures"].as_array().unwrap().is_empty());
}

#[test]
fn image_resources_list_add_replace_delete_and_extract() {
    let image = include_bytes!("../../../tests/test.jpg");
    let pdf = image_artifacts_to_pdf(
        &[Artifact::image(image)],
        &ImageToPdfOptions {
            layout: Some("original_size".to_owned()),
        },
        &ResourceLimits::default(),
    )
    .unwrap();

    let report = inspect_pdf_images(&pdf.bytes, &ImageInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert_eq!(report["images"][0]["name"], "Im1");

    let extracted = extract_pdf_image(
        &pdf.bytes,
        &ImageExtractOptions {
            name: "Im1".to_owned(),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    assert!(!extracted.bytes.is_empty());

    let added = edit_pdf_images_artifacts(
        &[Artifact::pdf(&empty_page_pdf()), Artifact::image(image)],
        &ImageEditOptions {
            action: ImageEditAction::Add,
            name: Some("Logo".to_owned()),
            page: Some(1),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let added_doc = lopdf::Document::load_mem(&added.bytes).unwrap();
    assert!(page_resources(&added_doc, 1).has(b"XObject"));

    let replaced = edit_pdf_images_artifacts(
        &[Artifact::pdf(&added.bytes), Artifact::image(image)],
        &ImageEditOptions {
            action: ImageEditAction::Replace,
            name: Some("Logo".to_owned()),
            page: None,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = inspect_pdf_images(&replaced.bytes, &ImageInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert_eq!(report["images"][0]["name"], "Logo");

    let deleted = edit_pdf_images_artifacts(
        &[Artifact::pdf(&replaced.bytes)],
        &ImageEditOptions {
            action: ImageEditAction::Delete,
            name: Some("Logo".to_owned()),
            page: None,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = inspect_pdf_images(&deleted.bytes, &ImageInspectOptions::default())
        .unwrap()
        .text;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert!(report["images"].as_array().unwrap().is_empty());
}

#[test]
fn image_resources_reject_malformed_xobject_dictionary() {
    let pdf = pdf_with_malformed_xobject_resources();

    let err = inspect_pdf_images(&pdf, &ImageInspectOptions::default()).unwrap_err();
    assert!(matches!(err, OxideError::ParsePdf));

    let err = edit_pdf_images_artifacts(
        &[Artifact::pdf(&pdf)],
        &ImageEditOptions {
            action: ImageEditAction::Delete,
            name: Some("Logo".to_owned()),
            page: None,
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();
    assert!(matches!(err, OxideError::ParsePdf));
}

#[test]
fn color_operations_rewrite_simple_content_and_reject_rasterize_pages() {
    let pdf = pdf_with_rgb_fill_content();
    let inverted = edit_pdf_colors(
        &pdf,
        &ColorEditOptions {
            action: ColorEditAction::Invert,
            pages: Some("1".to_owned()),
            from: None,
            to: None,
            factor: None,
            rasterize_pages: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&inverted.bytes).unwrap();
    assert_eq!(page_rgb_operator(&document, 1, "rg"), Some([0.0, 1.0, 1.0]));

    let replaced = edit_pdf_colors(
        &pdf,
        &ColorEditOptions {
            action: ColorEditAction::Replace,
            pages: Some("1".to_owned()),
            from: Some([1.0, 0.0, 0.0]),
            to: Some([0.0, 0.0, 1.0]),
            factor: None,
            rasterize_pages: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&replaced.bytes).unwrap();
    assert_eq!(page_rgb_operator(&document, 1, "rg"), Some([0.0, 0.0, 1.0]));

    let err = edit_pdf_colors(
        &pdf,
        &ColorEditOptions {
            action: ColorEditAction::Contrast,
            pages: None,
            from: None,
            to: None,
            factor: Some(1.25),
            rasterize_pages: true,
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();
    assert!(matches!(err, OxideError::UnsupportedPdfFeature { .. }));
    assert!(err.to_string().contains("rasterize_pages"));
}

#[test]
fn image_artifacts_to_pdf_converts_real_jpeg() {
    let image = include_bytes!("../../../tests/test.jpg");

    let pdf = image_artifacts_to_pdf(
        &[Artifact::image(image)],
        &ImageToPdfOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&pdf.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 1);
}

#[test]
fn image_artifacts_to_pdf_writes_one_page_per_image() {
    let image = include_bytes!("../../../tests/test.jpg");

    let pdf = image_artifacts_to_pdf(
        &[Artifact::image(image), Artifact::image(image)],
        &ImageToPdfOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&pdf.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 2);
}

#[test]
fn image_artifacts_to_pdf_enforces_pixel_limit() {
    let image = include_bytes!("../../../tests/test.jpg");
    let limits = ResourceLimits {
        max_pixels: Some(1),
        ..ResourceLimits::default()
    };

    let err = image_artifacts_to_pdf(
        &[Artifact::image(image)],
        &ImageToPdfOptions::default(),
        &limits,
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::ResourceLimitExceeded {
            limit: "max_pixels".to_owned()
        }
    );
}

#[test]
fn image_artifacts_to_pdf_rejects_unknown_image_format() {
    let err = image_artifacts_to_pdf(
        &[Artifact::image(b"not an image")],
        &ImageToPdfOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(err, OxideError::ImageDecode);
}

#[test]
fn image_artifacts_to_pdf_enforces_output_size_limit() {
    let image = include_bytes!("../../../tests/test.jpg");

    let err = image_artifacts_to_pdf(
        &[Artifact::image(image)],
        &ImageToPdfOptions::default(),
        &ResourceLimits {
            max_output_bytes: Some(1),
            ..ResourceLimits::default()
        },
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::ResourceLimitExceeded {
            limit: "max_output_bytes".to_owned()
        }
    );
}

#[test]
fn svg_to_pdf_converts_vector_svg_to_parseable_pdf() {
    let svg = br##"<svg xmlns="http://www.w3.org/2000/svg" width="120" height="80">
            <rect x="10" y="10" width="100" height="60" fill="#0077cc"/>
        </svg>"##;

    let pdf = svg_to_pdf(svg, &SvgToPdfOptions::default(), &ResourceLimits::default()).unwrap();
    let document = lopdf::Document::load_mem(&pdf.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 1);
}

#[test]
fn svg_to_pdf_rasterizes_only_when_requested() {
    let svg = br##"<svg xmlns="http://www.w3.org/2000/svg" width="120" height="80">
            <circle cx="60" cy="40" r="30" fill="#ef4444"/>
        </svg>"##;

    let pdf = svg_to_pdf(
        svg,
        &SvgToPdfOptions { rasterize: true },
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&pdf.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 1);
}

#[test]
fn svg_to_pdf_rejects_invalid_svg() {
    let err = svg_to_pdf(
        b"<svg><broken>",
        &SvgToPdfOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(err, OxideError::SvgParse);
}

#[test]
fn svg_to_pdf_rejects_non_svg_magic_bytes() {
    let err = svg_to_pdf(
        b"%PDF-1.7\nnot svg",
        &SvgToPdfOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(err, OxideError::SvgParse);
}

#[test]
fn render_pdf_page_writes_png_for_real_pdf() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let image = render_pdf_page(
        pdf,
        &RenderOptions {
            page: 1,
            format: Some("png".to_owned()),
            scale: Some(1.0),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let decoded = image::load_from_memory(&image.bytes).unwrap();

    assert!(decoded.width() > 0);
    assert!(decoded.height() > 0);
}

#[test]
fn render_pdf_page_rejects_out_of_range_page() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let err = render_pdf_page(
        pdf,
        &RenderOptions {
            page: 99,
            format: Some("png".to_owned()),
            scale: Some(1.0),
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::InvalidInput { .. }));
    assert!(err.to_string().contains("page 99 is out of range"));
}

#[test]
fn extract_text_from_pdf_returns_plain_text_for_real_pdf() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let text = extract_text_from_pdf(
        pdf,
        &ExtractTextOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap();

    assert!(!text.text.trim().is_empty());
    assert!(text.diagnostics.is_empty());
}

#[test]
fn extract_text_from_pdf_rejects_pdf_without_text_layer() {
    let pdf = empty_page_pdf();

    let err = extract_text_from_pdf(
        &pdf,
        &ExtractTextOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::InvalidInput { .. }));
    assert!(err.to_string().contains("no extractable text layer"));
}

#[test]
fn extract_text_from_pdf_rejects_unknown_format() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let err = extract_text_from_pdf(
        pdf,
        &ExtractTextOptions {
            format: Some("json".to_owned()),
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::InvalidInput { .. }));
    assert!(err
        .to_string()
        .contains("unsupported text extraction format"));
}

#[test]
fn extract_text_from_pdf_rejects_non_pdf_magic_bytes() {
    let err = extract_text_from_pdf(
        b"<svg></svg>",
        &ExtractTextOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::InvalidInput { .. }));
    assert!(err.to_string().contains("expected PDF"));
}

#[test]
fn watermark_pdf_adds_text_watermark_to_selected_page() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let watermarked = watermark_pdf_artifacts(
        &[Artifact::pdf(pdf)],
        &WatermarkOptions {
            kind: WatermarkKind::Text,
            text: Some("DRAFT".to_owned()),
            font: Some("DejaVu Sans".to_owned()),
            font_path: None,
            font_size: Some(36.0),
            opacity: Some(0.4),
            rotation: Some(30.0),
            position: Some("center".to_owned()),
            pages: Some("1".to_owned()),
            scale: None,
            rasterize: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&watermarked.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 3);
    assert!(page_resources(&document, 1).has(b"Font"));
    assert!(page_resources(&document, 1).has(b"ExtGState"));
    assert!(page_content_contains_operator(&document, 1, "Tj"));
    assert!(!page_content_contains_operator(&document, 2, "Tj"));
}

#[test]
fn watermark_pdf_rejects_missing_text_font_without_substitution() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let err = watermark_pdf_artifacts(
        &[Artifact::pdf(pdf)],
        &WatermarkOptions {
            kind: WatermarkKind::Text,
            text: Some("DRAFT".to_owned()),
            font: Some("Definitely Missing Font Family".to_owned()),
            font_path: None,
            font_size: Some(36.0),
            opacity: Some(0.4),
            rotation: None,
            position: Some("center".to_owned()),
            pages: Some("1".to_owned()),
            scale: None,
            rasterize: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(err, OxideError::FontResolution);
}

#[test]
fn watermark_pdf_enforces_image_pixel_limit() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let image = include_bytes!("../../../tests/test.jpg");

    let err = watermark_pdf_artifacts(
        &[Artifact::pdf(pdf), Artifact::image(image)],
        &WatermarkOptions {
            kind: WatermarkKind::Image,
            text: None,
            font: None,
            font_path: None,
            font_size: None,
            opacity: None,
            rotation: None,
            position: None,
            pages: None,
            scale: None,
            rasterize: false,
        },
        &ResourceLimits {
            max_pixels: Some(1),
            ..ResourceLimits::default()
        },
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::ResourceLimitExceeded {
            limit: "max_pixels".to_owned()
        }
    );
}

#[test]
fn watermark_pdf_adds_image_watermark_to_selected_page() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let image = include_bytes!("../../../tests/test.jpg");

    let watermarked = watermark_pdf_artifacts(
        &[Artifact::pdf(pdf), Artifact::image(image)],
        &WatermarkOptions {
            kind: WatermarkKind::Image,
            text: None,
            font: None,
            font_path: None,
            font_size: None,
            opacity: Some(0.3),
            rotation: Some(15.0),
            position: Some("bottom_right".to_owned()),
            pages: Some("2".to_owned()),
            scale: Some(0.25),
            rasterize: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&watermarked.bytes).unwrap();

    assert!(page_resources(&document, 2).has(b"XObject"));
    assert!(page_content_contains_operator(&document, 2, "Do"));
    assert!(!page_content_contains_operator(&document, 1, "Do"));
}

#[test]
fn watermark_pdf_adds_svg_watermark_as_vector_xobject() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let svg = simple_svg();

    let watermarked = watermark_pdf_artifacts(
        &[Artifact::pdf(pdf), Artifact::svg(svg)],
        &WatermarkOptions {
            kind: WatermarkKind::Svg,
            text: None,
            font: None,
            font_path: None,
            font_size: None,
            opacity: Some(0.5),
            rotation: None,
            position: Some("top_left".to_owned()),
            pages: Some("3".to_owned()),
            scale: Some(0.2),
            rasterize: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&watermarked.bytes).unwrap();

    assert!(page_resources(&document, 3).has(b"XObject"));
    assert!(page_content_contains_operator(&document, 3, "Do"));
    assert!(page_xobject_subtypes(&document, 3).contains(&b"Form".to_vec()));
    let form_operators = page_form_xobject_operators(&document, 3);
    assert!(form_operators.iter().any(|operator| operator == "f"));
    assert!(!form_operators
        .windows(2)
        .any(|operators| operators == ["re", "S"]));
}

#[test]
fn watermark_pdf_rasterizes_svg_only_when_requested() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let svg = simple_svg();

    let watermarked = watermark_pdf_artifacts(
        &[Artifact::pdf(pdf), Artifact::svg(svg)],
        &WatermarkOptions {
            kind: WatermarkKind::Svg,
            text: None,
            font: None,
            font_path: None,
            font_size: None,
            opacity: Some(0.5),
            rotation: None,
            position: Some("top_left".to_owned()),
            pages: Some("1".to_owned()),
            scale: Some(0.2),
            rasterize: true,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&watermarked.bytes).unwrap();

    assert!(page_xobject_subtypes(&document, 1).contains(&b"Image".to_vec()));
}

#[test]
fn watermark_pdf_rejects_malformed_svg_without_panic() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let err = watermark_pdf_artifacts(
        &[Artifact::pdf(pdf), Artifact::svg(b"<svg><broken>")],
        &WatermarkOptions {
            kind: WatermarkKind::Svg,
            text: None,
            font: None,
            font_path: None,
            font_size: None,
            opacity: None,
            rotation: None,
            position: None,
            pages: None,
            scale: None,
            rasterize: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(err, OxideError::SvgParse);
}
