//! Integration tests for the `overlay` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
include!("overlay/overlay_pdf_page_and_signature_appearance_are_visual_only.rs");
include!("overlay/image_artifacts_to_pdf_enforces_output_size_limit.rs");
include!("overlay/watermark_pdf_adds_svg_watermark_as_vector_xobject.rs");
