//! Integration tests for the `page_ops` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn merge_pdf_artifacts_combines_pages() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let merged = merge_pdf_artifacts(&[Artifact::pdf(pdf), Artifact::pdf(pdf)]).unwrap();
    let document = lopdf::Document::load_mem(&merged.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 6);
}

#[test]
fn merge_pdf_artifacts_enforces_input_and_page_limits() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let input_err = merge_pdf_artifacts_with_limits(
        &[Artifact::pdf(pdf), Artifact::pdf(pdf)],
        &ResourceLimits {
            max_input_bytes: Some(1),
            ..ResourceLimits::default()
        },
    )
    .unwrap_err();
    assert_eq!(
        input_err,
        OxideError::ResourceLimitExceeded {
            limit: "max_input_bytes".to_owned()
        }
    );

    let page_err = merge_pdf_artifacts_with_limits(
        &[Artifact::pdf(pdf), Artifact::pdf(pdf)],
        &ResourceLimits {
            max_pages: Some(5),
            ..ResourceLimits::default()
        },
    )
    .unwrap_err();
    assert_eq!(
        page_err,
        OxideError::ResourceLimitExceeded {
            limit: "max_pages".to_owned()
        }
    );
}

#[test]
fn split_pdf_keeps_only_selected_pages() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let split = split_pdf(pdf, "2-3").unwrap();
    let document = lopdf::Document::load_mem(&split.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 2);
    assert_page_numbers(&document, &[1, 2]);
}

#[test]
fn split_pdf_enforces_resource_limits() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let err = split_pdf_with_limits(
        pdf,
        "1",
        &ResourceLimits {
            max_pages: Some(2),
            ..ResourceLimits::default()
        },
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::ResourceLimitExceeded {
            limit: "max_pages".to_owned()
        }
    );
}

#[test]
fn reorder_pdf_rearranges_pages() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let reordered = reorder_pdf(pdf, "3,1,2").unwrap();
    let document = lopdf::Document::load_mem(&reordered.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 3);
    assert_page_numbers(&document, &[1, 2, 3]);
}

#[test]
fn rotate_pdf_updates_page_rotation() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let rotated = rotate_pdf(pdf, "1-2", 90).unwrap();
    let document = lopdf::Document::load_mem(&rotated.bytes).unwrap();

    assert_eq!(page_rotation(&document, 1), 90);
    assert_eq!(page_rotation(&document, 2), 90);
    assert_eq!(page_rotation(&document, 3), 0);
}

#[test]
fn rotate_pdf_rejects_non_pdf_magic_bytes() {
    let err =
        rotate_pdf_with_limits(b"not a pdf", "1", 90, &ResourceLimits::default()).unwrap_err();

    assert!(matches!(err, OxideError::InvalidInput { .. }));
    assert!(err.to_string().contains("expected PDF"));
}

#[test]
fn delete_pdf_pages_removes_selected_pages() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let deleted = delete_pdf_pages(pdf, "2").unwrap();
    let document = lopdf::Document::load_mem(&deleted.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 2);
}

#[test]
fn delete_pdf_pages_rejects_deleting_every_page() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let err = delete_pdf_pages(pdf, "1-3").unwrap_err();

    assert!(matches!(err, OxideError::InvalidInput { .. }));
    assert!(err.to_string().contains("leave at least one page"));
}

#[test]
fn extract_pdf_pages_keeps_selected_order() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let extracted = extract_pdf_pages(pdf, "3,1").unwrap();
    let document = lopdf::Document::load_mem(&extracted.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 2);
    assert_page_numbers(&document, &[1, 2]);
}

#[test]
fn delete_blank_pdf_pages_uses_object_level_blank_detection() {
    let pdf = pdf_with_blank_and_marked_page();

    let deleted = delete_blank_pdf_pages(&pdf, &DeleteBlankPagesOptions::default()).unwrap();
    let document = lopdf::Document::load_mem(&deleted.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 1);
}

#[test]
fn delete_blank_pdf_pages_rejects_unresolved_resource_reference() {
    let pdf = pdf_with_blank_page_and_missing_resources();

    let err = delete_blank_pdf_pages(&pdf, &DeleteBlankPagesOptions::default()).unwrap_err();

    assert!(matches!(err, OxideError::ParsePdf));
}

#[test]
fn crop_pdf_pages_sets_crop_box_on_selected_pages() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let cropped = crop_pdf_pages(
        pdf,
        &CropPagesOptions {
            pages: Some("1".to_owned()),
            left: 10.0,
            bottom: 20.0,
            right: 300.0,
            top: 400.0,
        },
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&cropped.bytes).unwrap();

    assert_eq!(
        page_box(&document, 1, b"CropBox"),
        [10.0, 20.0, 300.0, 400.0]
    );
    assert!(page_optional_box(&document, 2, b"CropBox").is_none());
}

#[test]
fn scale_pdf_pages_scales_page_box_and_content_stream() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let scaled = scale_pdf_pages(
        pdf,
        &ScalePagesOptions {
            pages: Some("1".to_owned()),
            factor: 0.5,
        },
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&scaled.bytes).unwrap();
    let media_box = page_box(&document, 1, b"MediaBox");

    assert_eq!(media_box[2], 306.0);
    assert!(page_content_contains(&document, 1, "cm"));
    assert_eq!(page_box(&document, 2, b"MediaBox")[2], 612.0);
}

#[test]
fn pdf_to_single_page_combines_pages_into_one_tall_page() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let single = pdf_to_single_page(pdf, &SinglePageOptions::default()).unwrap();
    let document = lopdf::Document::load_mem(&single.bytes).unwrap();
    let media_box = page_box(&document, 1, b"MediaBox");

    assert_eq!(document.get_pages().len(), 1);
    assert_eq!(media_box[2], 612.0);
    assert_eq!(media_box[3], 2376.0);
}

#[test]
fn nup_pdf_pages_places_source_pages_as_xobjects() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let nup = nup_pdf_pages(
        pdf,
        &NUpOptions {
            columns: 2,
            rows: 2,
        },
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&nup.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 1);
    assert_eq!(page_xobject_count(&document, 1), 3);
    assert_eq!(
        page_box(&document, 1, b"MediaBox"),
        [0.0, 0.0, 612.0, 792.0]
    );
    assert!(page_content_contains_operator(&document, 1, "Do"));
}

#[test]
fn nup_pdf_pages_rejects_zero_columns() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let err = nup_pdf_pages(
        pdf,
        &NUpOptions {
            columns: 0,
            rows: 2,
        },
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::InvalidInput { .. }));
    assert!(err.to_string().contains("greater than zero"));
}

#[test]
fn booklet_pdf_pages_outputs_two_up_imposed_pages() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let booklet = booklet_pdf_pages(pdf, &BookletOptions::default()).unwrap();
    let document = lopdf::Document::load_mem(&booklet.bytes).unwrap();

    assert_eq!(document.get_pages().len(), 2);
    assert_eq!(page_xobject_count(&document, 1), 1);
    assert_eq!(page_xobject_count(&document, 2), 2);
    assert!(page_content_contains_operator(&document, 1, "Do"));
}

#[test]
fn add_pdf_page_numbers_writes_selected_page_content() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let numbered = add_pdf_page_numbers(
        pdf,
        &PageNumbersOptions {
            pages: Some("2-3".to_owned()),
            start: 7,
            prefix: "p".to_owned(),
            suffix: String::new(),
            font_size: 10.0,
            position: PageNumberPosition::BottomRight,
        },
    )
    .unwrap();
    let document = lopdf::Document::load_mem(&numbered.bytes).unwrap();

    assert!(!page_content_text_contains(&document, 1, "p7"));
    assert!(page_content_text_contains(&document, 2, "p7"));
    assert!(page_content_text_contains(&document, 3, "p8"));
}

#[test]
fn add_pdf_page_numbers_rejects_non_ascii_text() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let err = add_pdf_page_numbers(
        pdf,
        &PageNumbersOptions {
            prefix: "第".to_owned(),
            ..PageNumbersOptions::default()
        },
    )
    .unwrap_err();

    assert!(matches!(err, OxideError::InvalidInput { .. }));
    assert!(err.to_string().contains("ASCII"));
}
