//! Integration tests for the `security` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn pdf_security_encrypts_with_aes256_and_decrypts_with_correct_password() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let encrypted = encrypt_pdf(
        pdf,
        &SecurityEncryptOptions {
            owner_password: "owner-pass".to_owned(),
            user_password: "user-pass".to_owned(),
            algorithm: EncryptionAlgorithm::Aes256,
            permissions: PermissionPolicy::default(),
        },
        &ResourceLimits::default(),
    )
    .unwrap();

    let encrypted_document = lopdf::Document::load_mem(&encrypted.bytes).unwrap();
    assert!(encrypted_document.is_encrypted());
    let encrypted_dict = encrypted_document.get_encrypted().unwrap();
    assert_eq!(encrypted_dict.get(b"V").unwrap().as_i64().unwrap(), 5);
    assert_eq!(encrypted_dict.get(b"R").unwrap().as_i64().unwrap(), 6);

    let decrypted = decrypt_pdf(
        &encrypted.bytes,
        &SecurityDecryptOptions {
            password: Some("user-pass".to_owned()),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let decrypted_document = lopdf::Document::load_mem(&decrypted.bytes).unwrap();
    assert!(!decrypted_document.is_encrypted());
    assert_eq!(decrypted_document.get_pages().len(), 3);
}

#[test]
fn pdf_security_rejects_wrong_or_missing_password_without_decrypted_output() {
    let encrypted = encrypt_pdf(
        &empty_page_pdf(),
        &SecurityEncryptOptions {
            owner_password: "owner-pass".to_owned(),
            user_password: "user-pass".to_owned(),
            algorithm: EncryptionAlgorithm::Aes256,
            permissions: PermissionPolicy::default(),
        },
        &ResourceLimits::default(),
    )
    .unwrap();

    let wrong = decrypt_pdf(
        &encrypted.bytes,
        &SecurityDecryptOptions {
            password: Some("wrong-pass".to_owned()),
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();
    assert_eq!(wrong, OxideError::IncorrectPassword);

    let missing = decrypt_pdf(
        &encrypted.bytes,
        &SecurityDecryptOptions { password: None },
        &ResourceLimits::default(),
    )
    .unwrap_err();
    assert_eq!(missing, OxideError::EncryptedPdf);
}

#[test]
fn pdf_security_reports_and_sets_permission_policy() {
    let restricted = PermissionPolicy {
        print: true,
        modify: false,
        copy: false,
        annotate: false,
        fill_forms: true,
        accessibility: true,
        assemble: false,
        high_quality_print: true,
    };
    let encrypted = encrypt_pdf(
        &empty_page_pdf(),
        &SecurityEncryptOptions {
            owner_password: "owner-pass".to_owned(),
            user_password: "user-pass".to_owned(),
            algorithm: EncryptionAlgorithm::Aes256,
            permissions: restricted.clone(),
        },
        &ResourceLimits::default(),
    )
    .unwrap();

    let report_text = inspect_pdf_permissions(
        &encrypted.bytes,
        &SecurityPermissionGetOptions {
            password: Some("owner-pass".to_owned()),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report: PermissionReport = serde_json::from_str(&report_text.text).unwrap();
    assert!(report.encrypted);
    assert_eq!(report.revision, Some(6));
    assert_eq!(report.permissions.copy, restricted.copy);
    assert_eq!(report.permissions.modify, restricted.modify);
    assert_eq!(report.permissions.fill_forms, restricted.fill_forms);

    let updated = set_pdf_permissions(
        &encrypted.bytes,
        &SecurityPermissionSetOptions {
            owner_password: "owner-pass".to_owned(),
            user_password: "new-user-pass".to_owned(),
            algorithm: EncryptionAlgorithm::Aes256,
            permissions: PermissionPolicy {
                copy: true,
                modify: true,
                ..restricted
            },
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let updated_report: PermissionReport = serde_json::from_str(
        &inspect_pdf_permissions(
            &updated.bytes,
            &SecurityPermissionGetOptions {
                password: Some("new-user-pass".to_owned()),
            },
            &ResourceLimits::default(),
        )
        .unwrap()
        .text,
    )
    .unwrap();
    assert!(updated_report.permissions.copy);
    assert!(updated_report.permissions.modify);
}

#[test]
fn pdf_security_rejects_rc4_and_unsupported_revisions() {
    let rc4 = encrypt_pdf(
        &empty_page_pdf(),
        &SecurityEncryptOptions {
            owner_password: "owner-pass".to_owned(),
            user_password: "user-pass".to_owned(),
            algorithm: EncryptionAlgorithm::Rc4,
            permissions: PermissionPolicy::default(),
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();
    assert!(matches!(rc4, OxideError::UnsupportedPdfFeature { .. }));

    let unsupported = encrypted_pdf_with_revision(2);
    let err = decrypt_pdf(
        &unsupported,
        &SecurityDecryptOptions {
            password: Some("user-pass".to_owned()),
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();
    assert!(matches!(err, OxideError::UnsupportedPdfFeature { .. }));
}
