//! Integration tests for the `signatures` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
include!("signatures/signature_field_delete_refuses_signed_field_without_destructive_flag.rs");
include!("signatures/verify_pdf_signatures_reports_malformed_byte_range_as_invalid.rs");
