//! Integration tests for the `signatures` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;
use std::path::PathBuf;

#[test]
fn signature_field_delete_refuses_signed_field_without_destructive_flag() {
    let pdf = pdf_with_signature_dictionary(vec![0, 64, 192, 64], vec![0x30, 0x82]);

    let err = delete_pdf_signature_field(
        &pdf,
        &SignatureDeleteFieldOptions {
            field_name: "Approval".to_owned(),
            destructive: false,
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::InvalidInput {
            reason: "signature field contains signed value material; pass destructive delete explicitly to remove it".to_owned()
        }
    );
}

#[test]
fn signature_field_delete_removes_field_when_destructive_is_explicit() {
    let pdf = pdf_with_signature_dictionary(vec![0, 64, 192, 64], vec![0x30, 0x82]);

    let deleted = delete_pdf_signature_field(
        &pdf,
        &SignatureDeleteFieldOptions {
            field_name: "Approval".to_owned(),
            destructive: true,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = verify_pdf_signatures(
        &deleted,
        &SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(write_test_trust_anchors("delete_signature_field")),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report: SignatureVerificationReport = serde_json::from_str(&report.text).unwrap();

    assert_eq!(report.verdict, SignatureVerdict::Indeterminate);
    assert!(report.signatures.is_empty());
    assert!(report
        .diagnostics
        .iter()
        .any(|diagnostic| diagnostic.code == "no_signatures"));
}

#[test]
fn add_signature_creates_pdf_that_verifies_and_detects_tamper() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let (certificate_path, private_key_path) = write_p256_signing_material("add_signature");

    let signed_pdf = add_pdf_signature(
        pdf,
        &SignatureAddOptions {
            field_name: "Approval".to_owned(),
            certificate: certificate_path.clone(),
            private_key: private_key_path,
            contents_reserved_bytes: Some(16_384),
            appearance_field: None,
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report = verify_pdf_signatures(
        &signed_pdf,
        &SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(certificate_path.clone()),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report: SignatureVerificationReport = serde_json::from_str(&report.text).unwrap();

    assert_eq!(report.signatures.len(), 1);
    assert_eq!(report.signatures[0].field_name.as_deref(), Some("Approval"));
    assert_eq!(
        report.signatures[0].digest_status.status,
        SignatureCheckState::Passed
    );
    assert_eq!(
        report.signatures[0].signature_status.status,
        SignatureCheckState::Passed
    );
    assert_eq!(
        report.signatures[0].certificate_chain_status.status,
        SignatureCheckState::Passed
    );

    let mut tampered = signed_pdf.clone();
    let byte_range = report.signatures[0].byte_range.values.unwrap();
    let tamper_index = usize::try_from(byte_range[1] / 2).unwrap();
    tampered[tamper_index] ^= 0x01;
    let tampered_report = verify_pdf_signatures(
        &tampered,
        &SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(certificate_path),
        },
        &ResourceLimits::default(),
    );
    assert!(
        tampered_report.is_err() || {
            let report: SignatureVerificationReport =
                serde_json::from_str(&tampered_report.unwrap().text).unwrap();
            report.verdict == SignatureVerdict::Invalid
                || report
                    .signatures
                    .iter()
                    .any(|signature| signature.digest_status.status == SignatureCheckState::Failed)
        }
    );
}

#[test]
fn timestamp_add_requires_exactly_one_timestamp_source() {
    let pdf = include_bytes!("../../../tests/test.pdf");

    let err = add_pdf_timestamp(
        pdf,
        &TimestampAddOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::InvalidInput {
            reason: "timestamp add requires exactly one of tsa_url or token".to_owned()
        }
    );
}

#[test]
fn timestamp_add_reports_invalid_explicit_token_without_modifying_pdf() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let token_path = std::env::temp_dir().join(format!(
        "oxidepdf_core_invalid_timestamp_{}.tsr",
        std::process::id()
    ));
    std::fs::write(&token_path, b"not cms der").unwrap();

    let report = add_pdf_timestamp(
        pdf,
        &TimestampAddOptions {
            tsa_url: None,
            token: Some(token_path),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report: TimestampReport = serde_json::from_str(&report.text).unwrap();

    assert_eq!(report.status.status, SignatureCheckState::Failed);
    assert!(report.input_preserved);
    assert!(report
        .diagnostics
        .iter()
        .any(|diagnostic| diagnostic.code == "timestamp_not_embedded"));
}

#[test]
fn add_signature_validates_inputs_without_leaking_key_paths() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let err = add_pdf_signature(
        pdf,
        &SignatureAddOptions {
            field_name: String::new(),
            certificate: PathBuf::from("/sensitive/cert.pem"),
            private_key: PathBuf::from("/sensitive/private-key.pem"),
            contents_reserved_bytes: None,
            appearance_field: None,
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();
    let message = err.to_string();

    assert!(message.contains("signature field name must not be empty"));
    assert!(!message.contains("/sensitive"));
    assert!(!message.contains("private-key.pem"));
}

#[test]
fn verify_pdf_signatures_without_trust_anchors_is_indeterminate_not_trusted() {
    let pdf = pdf_with_signature_dictionary(vec![0, 64, 192, 64], vec![0x30, 0x82]);

    let report = verify_pdf_signatures(
        &pdf,
        &SignatureOptions::default(),
        &ResourceLimits::default(),
    )
    .unwrap();
    let report: SignatureVerificationReport = serde_json::from_str(&report.text).unwrap();

    assert_ne!(report.verdict, SignatureVerdict::Trusted);
    assert_eq!(report.trust_anchor_count, 0);
    assert!(report
        .diagnostics
        .iter()
        .any(|diagnostic| diagnostic.code == "trust_anchors_missing"));
}

#[test]
fn verify_pdf_signatures_rejects_empty_trust_anchor_file() {
    let pdf = include_bytes!("../../../tests/fixtures/signature-placeholder.pdf");
    let trust_anchors = write_empty_trust_anchors("empty_signature_anchors");

    let err = verify_pdf_signatures(
        pdf,
        &SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(trust_anchors),
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::InvalidInput {
            reason: "trust anchors file contains no valid PEM certificates".to_owned()
        }
    );
}

#[test]
fn verify_pdf_signatures_rejects_invalid_trust_anchor_certificate() {
    let pdf = include_bytes!("../../../tests/fixtures/signature-placeholder.pdf");
    let trust_anchors = write_invalid_trust_anchors("invalid_signature_anchors");

    let err = verify_pdf_signatures(
        pdf,
        &SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(trust_anchors),
        },
        &ResourceLimits::default(),
    )
    .unwrap_err();

    assert_eq!(
        err,
        OxideError::InvalidInput {
            reason: "trust anchors file contains no valid PEM certificates".to_owned()
        }
    );
}

#[test]
fn verify_pdf_signatures_reports_unsigned_pdf_as_indeterminate() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let trust_anchors = write_test_trust_anchors("unsigned_pdf_report");

    let report = verify_pdf_signatures(
        pdf,
        &SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(trust_anchors),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report: SignatureVerificationReport = serde_json::from_str(&report.text).unwrap();

    assert_eq!(report.verdict, SignatureVerdict::Indeterminate);
    assert_eq!(report.trust_anchor_count, 1);
    assert!(report.signatures.is_empty());
    assert_eq!(report.diagnostics.len(), 1);
    assert_eq!(report.diagnostics[0].code, "no_signatures");
}

#[test]
fn verify_pdf_signatures_reports_malformed_byte_range_as_invalid() {
    let pdf = pdf_with_signature_dictionary(vec![0, 64, 32, 64], vec![0x30, 0x82]);
    let trust_anchors = write_test_trust_anchors("malformed_byte_range_report");

    let report = verify_pdf_signatures(
        &pdf,
        &SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(trust_anchors),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report: SignatureVerificationReport = serde_json::from_str(&report.text).unwrap();

    assert_eq!(report.verdict, SignatureVerdict::Invalid);
    assert_eq!(report.signatures.len(), 1);
    assert!(report.signatures[0]
        .diagnostics
        .iter()
        .any(|diagnostic| diagnostic.code == "byte_range_not_ordered"));
}

#[test]
fn verify_pdf_signatures_reports_unknown_subfilter_as_unsupported() {
    let pdf = pdf_with_signature_dictionary_and_subfilter(
        vec![0, 64, 192, 64],
        vec![0x30, 0x82],
        "adbe.x509.rsa_sha1",
    );
    let trust_anchors = write_test_trust_anchors("unknown_subfilter_report");

    let report = verify_pdf_signatures(
        &pdf,
        &SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(trust_anchors),
        },
        &ResourceLimits::default(),
    )
    .unwrap();
    let report: SignatureVerificationReport = serde_json::from_str(&report.text).unwrap();

    assert_eq!(report.verdict, SignatureVerdict::Unsupported);
    assert_eq!(report.signatures.len(), 1);
    assert!(report.signatures[0]
        .diagnostics
        .iter()
        .any(|diagnostic| diagnostic.code == "unsupported_subfilter"));
}

#[test]
fn signature_research_scanner_finds_signature_markers() {
    let pdf = include_bytes!("../../../tests/fixtures/signature-placeholder.pdf");

    let report = inspect_pdf_signature_markers_for_research(pdf).unwrap();

    assert_eq!(report.signature_dictionary_count, 1);
    assert_eq!(report.subfilters, vec!["adbe.pkcs7.detached"]);
    assert_eq!(report.byte_ranges.len(), 1);
    assert_eq!(report.byte_ranges[0].first_start, 0);
    assert_eq!(report.byte_ranges[0].first_len, 64);
    assert_eq!(report.byte_ranges[0].second_start, 192);
    assert_eq!(report.byte_ranges[0].second_len, 64);
    assert!(report.byte_ranges[0].in_bounds);
    assert!(report.byte_ranges[0].ordered_non_overlapping);
    assert_eq!(report.byte_ranges[0].gap_len, Some(128));
    assert_eq!(report.byte_ranges[0].covered_len, Some(128));
}

#[test]
fn signature_research_scanner_reports_out_of_bounds_byte_range() {
    let pdf = b"%PDF-1.7\n1 0 obj\n<< /Type /Sig /SubFilter /ETSI.CAdES.detached /ByteRange [0 5 999 10] >>\nendobj\n%%EOF";

    let report = inspect_pdf_signature_markers_for_research(pdf).unwrap();

    assert_eq!(report.signature_dictionary_count, 1);
    assert_eq!(report.subfilters, vec!["ETSI.CAdES.detached"]);
    assert_eq!(report.byte_ranges.len(), 1);
    assert!(!report.byte_ranges[0].in_bounds);
    assert!(report.byte_ranges[0].ordered_non_overlapping);
    assert_eq!(report.byte_ranges[0].covered_len, Some(15));
}

#[test]
fn signature_research_scanner_ignores_malformed_byte_range() {
    let pdf = b"%PDF-1.7\n1 0 obj\n<< /Type /Sig /ByteRange [0 nope 10 5] >>\nendobj\n%%EOF";

    let report = inspect_pdf_signature_markers_for_research(pdf).unwrap();

    assert_eq!(report.signature_dictionary_count, 1);
    assert!(report.byte_ranges.is_empty());
}

#[test]
fn signature_research_scanner_rejects_non_pdf_magic_bytes() {
    let err = inspect_pdf_signature_markers_for_research(b"not a pdf").unwrap_err();

    assert!(matches!(err, OxideError::InvalidInput { .. }));
    assert!(err.to_string().contains("expected PDF"));
}
