//! Integration tests for the `workflow` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
#[allow(unused_imports)]
use common::*;
#[allow(unused_imports)]
use oxidepdf_core::*;

#[test]
fn workflow_schema_version_starts_at_one() {
    assert_eq!(WORKFLOW_SCHEMA_VERSION, 1);
}

#[test]
fn parses_example_json_workflow() {
    let workflow: Workflow = serde_json::from_str(
        r#"
            {
              "version": 1,
              "inputs": [
                { "id": "source", "path": "./input.pdf" }
              ],
              "tasks": [
                {
                  "id": "rotate_pages",
                  "op": {
                    "pdf_edit": {
                      "rotate_pages": {
                        "pages": "1,3-5",
                        "degrees": 90
                      }
                    }
                  },
                  "inputs": ["source"]
                }
              ],
              "outputs": [
                { "id": "final", "from": "rotate_pages", "path": "./output.pdf" }
              ],
              "limits": {
                "max_input_bytes": 524288000,
                "max_pages": 5000,
                "max_pixels": 160000000
              },
              "metadata": {
                "title": "Example workflow"
              }
            }
            "#,
    )
    .unwrap();

    assert_eq!(workflow.version, WorkflowVersion::V1);
    assert_eq!(workflow.inputs[0].id.as_str(), "source");
    assert_eq!(workflow.tasks[0].id.as_str(), "rotate_pages");
    assert!(matches!(
        workflow.tasks[0].op,
        OperatorSpec::PdfEdit(PdfEditOptions::RotatePages(RotateOptions {
            degrees: 90,
            ..
        }))
    ));
    assert_eq!(workflow.outputs[0].from.as_str(), "rotate_pages");
}

#[test]
fn parses_example_yaml_workflow() {
    let workflow: Workflow = serde_yaml::from_str(
        r#"
            version: 1
            inputs:
              - id: source
                path: ./input.pdf
            tasks:
              - id: rotate_pages
                op:
                  pdf_edit:
                    rotate_pages:
                      pages: "1,3-5"
                      degrees: 90
                inputs: [source]
              - id: stamp
                op:
                  pdf_edit:
                    watermark:
                      kind: text
                      text: Confidential
                      opacity: 0.18
                      position: center
                inputs: [rotate_pages]
            outputs:
              - id: final
                from: stamp
                path: ./output.pdf
            limits:
              max_input_bytes: 524288000
              max_pages: 5000
              max_pixels: 160000000
            metadata:
              title: Example workflow
            "#,
    )
    .unwrap();

    assert_eq!(workflow.version, WorkflowVersion::V1);
    assert_eq!(workflow.tasks.len(), 2);
    assert!(matches!(
        workflow.tasks[1].op,
        OperatorSpec::PdfEdit(PdfEditOptions::Watermark(WatermarkOptions {
            kind: WatermarkKind::Text,
            ..
        }))
    ));
}

#[test]
fn parses_signature_workflow_operator_schema() {
    let workflow: Workflow = serde_yaml::from_str(
        r#"
            version: 1
            inputs:
              - id: source
                path: ./signed.pdf
            tasks:
              - id: verify
                op:
                  pdf_sign:
                    verify:
                      mode: verify
                      trust_anchors: ./anchors.pem
                inputs: [source]
            outputs:
              - id: final
                from: verify
                path: ./report.json
            "#,
    )
    .unwrap();

    assert!(matches!(
        workflow.tasks[0].op,
        OperatorSpec::PdfSign(PdfSignOptions::Verify(SignatureOptions {
            mode: SignatureMode::Verify,
            trust_anchors: Some(_),
        }))
    ));
    match &workflow.tasks[0].op {
        OperatorSpec::PdfSign(PdfSignOptions::Verify(options)) => {
            assert_eq!(
                options.trust_anchors.as_deref(),
                Some(std::path::Path::new("./anchors.pem"))
            );
        }
        _ => unreachable!("asserted signature operator above"),
    }
}

#[test]
fn parses_signature_list_workflow_operator_schema() {
    let workflow: Workflow = serde_yaml::from_str(
        r#"
            version: 1
            inputs:
              - id: source
                path: ./signed.pdf
            tasks:
              - id: list
                op:
                  pdf_sign:
                    list:
                      mode: list
                inputs: [source]
            outputs:
              - id: final
                from: list
                path: ./report.json
            "#,
    )
    .unwrap();

    assert!(matches!(
        workflow.tasks[0].op,
        OperatorSpec::PdfSign(PdfSignOptions::List(SignatureOptions {
            mode: SignatureMode::List,
            trust_anchors: None,
        }))
    ));
}

#[test]
fn parses_signature_mutation_workflow_operator_schema() {
    let workflow: Workflow = serde_yaml::from_str(
        r#"
            version: 1
            inputs:
              - id: source
                path: ./unsigned.pdf
            tasks:
              - id: add_sig
                op:
                  pdf_sign:
                    add:
                      field_name: Approval
                      certificate: ./cert.pem
                      private_key: ./key.pem
                      contents_reserved_bytes: 8192
                inputs: [source]
              - id: delete_sig
                op:
                  pdf_sign:
                    delete_field:
                      field_name: Approval
                      destructive: true
                inputs: [add_sig]
              - id: timestamp
                op:
                  pdf_sign:
                    timestamp:
                      token: ./timestamp.tsr
                inputs: [delete_sig]
            outputs:
              - id: final
                from: timestamp
                path: ./report.json
            "#,
    )
    .unwrap();

    assert!(matches!(
        workflow.tasks[0].op,
        OperatorSpec::PdfSign(PdfSignOptions::Add(SignatureAddOptions { .. }))
    ));
    assert!(matches!(
        workflow.tasks[1].op,
        OperatorSpec::PdfSign(PdfSignOptions::DeleteField(SignatureDeleteFieldOptions {
            destructive: true,
            ..
        }))
    ));
    assert!(matches!(
        workflow.tasks[2].op,
        OperatorSpec::PdfSign(PdfSignOptions::Timestamp(TimestampAddOptions {
            token: Some(_),
            tsa_url: None,
        }))
    ));
}

#[test]
fn parses_compare_workflow_operator_schema() {
    let workflow: Workflow = serde_yaml::from_str(
        r#"
            version: 1
            inputs:
              - id: left
                path: ./left.pdf
              - id: right
                path: ./right.pdf
            tasks:
              - id: compare
                op:
                  pdf_compare:
                    report:
                      include_text: false
                inputs: [left, right]
            outputs:
              - id: final
                from: compare
                path: ./report.json
            "#,
    )
    .unwrap();

    assert!(matches!(
        workflow.tasks[0].op,
        OperatorSpec::PdfCompare(PdfCompareOptions::Report(CompareOptions {
            include_text: false,
            ..
        }))
    ));
}

#[test]
fn parses_document_interaction_workflow_operator_schema() {
    let workflow: Workflow = serde_yaml::from_str(
        r#"
            version: 1
            inputs:
              - id: source
                path: ./input.pdf
              - id: attachment
                path: ./note.txt
            tasks:
              - id: metadata
                op:
                  pdf_edit:
                    metadata:
                      action: set
                      entries:
                        - key: title
                          value: Quarterly Report
                        - key: author
                          value: OxidePDF
                inputs: [source]
              - id: attach
                op:
                  pdf_edit:
                    attachment:
                      action: add
                      name: note.txt
                      description: Review note
                inputs: [metadata, attachment]
              - id: inspect_forms
                op:
                  pdf_inspect:
                    forms: {}
                inputs: [attach]
            outputs:
              - id: final
                from: inspect_forms
                path: ./forms.json
            "#,
    )
    .unwrap();

    assert!(matches!(
        workflow.tasks[0].op,
        OperatorSpec::PdfEdit(PdfEditOptions::Metadata(MetadataEditOptions {
            action: MetadataEditAction::Set,
            ..
        }))
    ));
    assert!(matches!(
        workflow.tasks[2].op,
        OperatorSpec::PdfInspect(PdfInspectOptions::Forms(FormInspectOptions {}))
    ));
}

#[test]
fn missing_required_workflow_field_fails() {
    let err = serde_json::from_str::<Workflow>(
        r#"
            {
              "version": 1,
              "inputs": [],
              "tasks": [],
              "limits": {},
              "metadata": {}
            }
            "#,
    )
    .unwrap_err();

    assert!(err.to_string().contains("outputs"));
}

#[test]
fn operator_spec_rejects_multiple_operator_keys() {
    let err = serde_json::from_str::<OperatorSpec>(
        r#"
            {
              "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } },
              "pdf_inspect": { "render": { "page": 1 } }
            }
            "#,
    )
    .unwrap_err();

    assert!(err
        .to_string()
        .contains("operator spec must contain exactly one operator"));
}

#[test]
fn operator_spec_rejects_removed_legacy_operator_keys() {
    let err = serde_json::from_str::<OperatorSpec>(
        r#"
            {
              "rotate": { "pages": "1", "degrees": 90 }
            }
            "#,
    )
    .unwrap_err();

    assert!(err.to_string().contains("unknown field"));
}

#[test]
fn error_codes_are_stable_machine_readable_values() {
    assert_eq!(
        OxideError::UnsupportedPdfFeature {
            feature: "object stream".to_owned()
        }
        .code(),
        "unsupported_pdf_feature"
    );
    assert_eq!(OxideError::EncryptedPdf.code(), "encrypted_pdf");
    assert_eq!(OxideError::IncorrectPassword.code(), "incorrect_password");
    assert_eq!(OxideError::FontResolution.code(), "font_resolution");
    assert_eq!(
        OxideError::ResourceLimitExceeded {
            limit: "max_pages".to_owned()
        }
        .code(),
        "resource_limit_exceeded"
    );
}

#[test]
fn linear_workflow_executes_tasks_in_dependency_order() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.pdf" }],
              "tasks": [
                {
                  "id": "rotate",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["source"]
                },
                {
                  "id": "render",
                  "op": { "pdf_inspect": { "render": { "page": 1, "format": "png", "scale": 1.0 } } },
                  "inputs": ["rotate"]
                }
              ],
              "outputs": [{ "id": "final", "from": "render", "path": "out.png" }]
            }
            "#,
    );
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("source"), Artifact::bytes(b"input"));
    let runner = RecordingRunner::default();

    let result = execute_workflow(&workflow, store, &runner).unwrap();

    assert_eq!(runner.executed(), ["rotate", "render"]);
    assert_eq!(
        result.store.get(&artifact_ref("render")),
        Some(&Artifact::bytes(b"render"))
    );
    assert_eq!(result.plan.task_order[0].as_str(), "rotate");
    assert_eq!(result.plan.task_order[1].as_str(), "render");
}

#[test]
fn execution_plan_exposes_task_index() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.pdf" }],
              "tasks": [
                {
                  "id": "rotate",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["source"]
                }
              ],
              "outputs": [{ "id": "final", "from": "rotate", "path": "out.pdf" }]
            }
            "#,
    );

    let plan = validate_workflow(&workflow).unwrap();

    // The index maps each task id to its slot in workflow.tasks, so execution
    // does not rebuild a lookup map on every run.
    let index = plan.task_index.get(&TaskId::new("rotate")).copied();
    assert_eq!(index, Some(0));
}

#[test]
fn intermediate_artifact_evicted_after_last_consumer() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.pdf" }],
              "tasks": [
                {
                  "id": "rotate",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["source"]
                },
                {
                  "id": "render",
                  "op": { "pdf_inspect": { "render": { "page": 1, "format": "png", "scale": 1.0 } } },
                  "inputs": ["rotate"]
                }
              ],
              "outputs": [{ "id": "final", "from": "render", "path": "out.png" }]
            }
            "#,
    );
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("source"), Artifact::bytes(b"input"));
    let runner = RecordingRunner::default();

    let result = execute_workflow(&workflow, store, &runner).unwrap();

    // "source" and "rotate" are fully consumed and not referenced by any
    // output, so they must be evicted; only the output artifact survives.
    assert_eq!(result.store.get(&artifact_ref("source")), None);
    assert_eq!(result.store.get(&artifact_ref("rotate")), None);
    assert!(result.store.get(&artifact_ref("render")).is_some());
}

#[test]
fn output_referenced_artifact_is_not_evicted() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.pdf" }],
              "tasks": [
                {
                  "id": "rotate",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["source"]
                },
                {
                  "id": "render",
                  "op": { "pdf_inspect": { "render": { "page": 1, "format": "png", "scale": 1.0 } } },
                  "inputs": ["rotate"]
                }
              ],
              "outputs": [
                { "id": "rotated", "from": "rotate", "path": "rotated.pdf" },
                { "id": "final", "from": "render", "path": "out.png" }
              ]
            }
            "#,
    );
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("source"), Artifact::bytes(b"input"));
    let runner = RecordingRunner::default();

    let result = execute_workflow(&workflow, store, &runner).unwrap();

    // "rotate" is consumed by "render" but is also an output, so it must stay.
    assert!(result.store.get(&artifact_ref("rotate")).is_some());
    assert!(result.store.get(&artifact_ref("render")).is_some());
}

#[test]
fn dag_workflow_topologically_sorts_before_execution() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.pdf" }],
              "tasks": [
                {
                  "id": "left",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["source"]
                },
                {
                  "id": "right",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 180 } } },
                  "inputs": ["source"]
                },
                {
                  "id": "join",
                  "op": { "pdf_edit": { "merge": {} } },
                  "inputs": ["left", "right"]
                }
              ],
              "outputs": [{ "id": "final", "from": "join", "path": "out.pdf" }]
            }
            "#,
    );

    let plan = validate_workflow(&workflow).unwrap();
    let left = plan
        .task_order
        .iter()
        .position(|id| id.as_str() == "left")
        .unwrap();
    let right = plan
        .task_order
        .iter()
        .position(|id| id.as_str() == "right")
        .unwrap();
    let join = plan
        .task_order
        .iter()
        .position(|id| id.as_str() == "join")
        .unwrap();

    assert!(left < join);
    assert!(right < join);

    // The plan also exposes parallel layers: the two independent rotations sit
    // in the first layer, and the merge that depends on both sits alone in the
    // second.
    assert_eq!(plan.layers.len(), 2);
    assert_eq!(plan.layers[0].len(), 2);
    assert_eq!(plan.layers[1].len(), 1);
    let join_index = plan
        .task_index
        .get(&oxidepdf_core::TaskId::new("join"))
        .copied()
        .unwrap();
    assert_eq!(plan.layers[1][0], join_index);
}

#[test]
fn cyclic_workflow_fails_validation() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [],
              "tasks": [
                {
                  "id": "a",
                  "op": { "pdf_edit": { "merge": {} } },
                  "inputs": ["b"]
                },
                {
                  "id": "b",
                  "op": { "pdf_edit": { "merge": {} } },
                  "inputs": ["a"]
                }
              ],
              "outputs": [{ "id": "final", "from": "b", "path": "out.pdf" }]
            }
            "#,
    );

    let err = validate_workflow(&workflow).unwrap_err();

    assert!(matches!(err, OxideError::InvalidWorkflow { .. }));
    assert!(err.to_string().contains("cycle"));
}

#[test]
fn missing_artifact_reference_fails_validation() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.pdf" }],
              "tasks": [
                {
                  "id": "rotate",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["missing"]
                }
              ],
              "outputs": [{ "id": "final", "from": "rotate", "path": "out.pdf" }]
            }
            "#,
    );

    let err = validate_workflow(&workflow).unwrap_err();

    assert!(matches!(err, OxideError::InvalidWorkflow { .. }));
    assert!(err.to_string().contains("missing"));
}

#[test]
fn duplicate_artifact_identifiers_fail_validation() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.pdf" }],
              "tasks": [
                {
                  "id": "source",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["source"]
                }
              ],
              "outputs": [{ "id": "final", "from": "source", "path": "out.pdf" }]
            }
            "#,
    );

    let err = validate_workflow(&workflow).unwrap_err();

    assert!(matches!(err, OxideError::InvalidWorkflow { .. }));
    assert!(err.to_string().contains("duplicate"));
}

#[test]
fn task_failure_stops_downstream_execution() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.pdf" }],
              "tasks": [
                {
                  "id": "fail",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["source"]
                },
                {
                  "id": "after",
                  "op": { "pdf_inspect": { "render": { "page": 1, "format": "png", "scale": 1.0 } } },
                  "inputs": ["fail"]
                }
              ],
              "outputs": [{ "id": "final", "from": "after", "path": "out.png" }]
            }
            "#,
    );
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("source"), Artifact::bytes(b"input"));
    let expected = OxideError::InvalidInput {
        reason: "runner failed".to_owned(),
    };
    let runner = RecordingRunner::with_failure("fail", expected.clone());

    let err = execute_workflow(&workflow, store, &runner).unwrap_err();

    assert_eq!(err, expected);
    assert_eq!(runner.executed(), ["fail"]);
}

#[test]
fn parses_overlay_image_color_operator_schema() {
    let workflow: Workflow = serde_yaml::from_str(
        r#"
        version: 1
        inputs:
          - id: pdf
            path: ./input.pdf
          - id: overlay
            path: ./overlay.pdf
          - id: image
            path: ./image.png
        tasks:
          - id: stamp
            op:
              pdf_edit:
                overlay:
                  kind: stamp
                  text: APPROVED
                  pages: "1"
                  opacity: 0.7
            inputs: [pdf]
          - id: overlay_pdf
            op:
              pdf_edit:
                overlay:
                  kind: pdf_page
                  pages: "1"
                  source_page: 1
            inputs: [stamp, overlay]
          - id: image_replace
            op:
              pdf_edit:
                image_edit:
                  action: replace
                  name: Im1
            inputs: [overlay_pdf, image]
          - id: color
            op:
              pdf_edit:
                color:
                  action: invert
                  pages: "1"
            inputs: [image_replace]
          - id: list_images
            op:
              pdf_inspect:
                images: {}
            inputs: [color]
        outputs:
          - id: report
            from: list_images
            path: ./images.json
        "#,
    )
    .unwrap();

    assert_eq!(workflow.tasks.len(), 5);
}

#[test]
fn parses_compression_operator_schema() {
    let workflow: Workflow = serde_yaml::from_str(
        r#"
        version: 1
        inputs:
          - id: source
            path: ./input.pdf
        tasks:
          - id: compress
            op:
              pdf_edit:
                compression:
                  mode: lossless
            inputs: [source]
        outputs:
          - id: final
            from: compress
            path: ./output.pdf
        "#,
    )
    .unwrap();

    assert!(matches!(
        workflow.tasks[0].op,
        OperatorSpec::PdfEdit(PdfEditOptions::Compression(CompressionOptions {
            mode: CompressionMode::Lossless,
            images: None,
        }))
    ));
}

#[test]
fn parses_security_operator_schema() {
    let workflow: Workflow = serde_yaml::from_str(
        r#"
        version: 1
        inputs:
          - id: source
            path: ./input.pdf
        tasks:
          - id: encrypt
            op:
              pdf_security:
                encrypt:
                  owner_password: owner-pass
                  user_password: user-pass
                  algorithm: aes256
                  permissions:
                    print: true
                    modify: false
                    copy: false
                    annotate: false
                    fill_forms: true
                    accessibility: true
                    assemble: false
                    high_quality_print: true
            inputs: [source]
          - id: decrypt
            op:
              pdf_security:
                decrypt:
                  password: user-pass
            inputs: [encrypt]
          - id: permissions
            op:
              pdf_security:
                permissions_get:
                  password: owner-pass
            inputs: [encrypt]
        outputs:
          - id: final
            from: decrypt
            path: ./output.pdf
        "#,
    )
    .unwrap();

    assert!(matches!(
        workflow.tasks[0].op,
        OperatorSpec::PdfSecurity(PdfSecurityOptions::Encrypt(SecurityEncryptOptions {
            algorithm: EncryptionAlgorithm::Aes256,
            ..
        }))
    ));
    assert!(matches!(
        workflow.tasks[1].op,
        OperatorSpec::PdfSecurity(PdfSecurityOptions::Decrypt(_))
    ));
    assert!(matches!(
        workflow.tasks[2].op,
        OperatorSpec::PdfSecurity(PdfSecurityOptions::PermissionsGet(_))
    ));
}

#[test]
fn pdf_operator_runner_handles_page_editing_tasks() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let runner = PdfOperatorRunner::default();

    let merged = runner
        .run(
            &TaskSpec {
                id: TaskId::new("merge"),
                op: OperatorSpec::PdfEdit(PdfEditOptions::Merge(MergeOptions {})),
                inputs: vec![artifact_ref("a"), artifact_ref("b")],
            },
            &[Artifact::pdf(pdf), Artifact::pdf(pdf)],
        )
        .unwrap();

    // Object-level operators emit a parsed document; it must serialize back to
    // a valid PDF at the output boundary.
    assert!(matches!(merged, Artifact::PdfObject(_)));
    let bytes = merged.output_bytes().unwrap();
    assert!(bytes.starts_with(b"%PDF-"));
}

#[test]
fn pdf_operator_runner_enforces_output_size_limit() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let runner = PdfOperatorRunner::with_limits(ResourceLimits {
        max_output_bytes: Some(1),
        ..ResourceLimits::default()
    });

    let err = runner
        .run(
            &TaskSpec {
                id: TaskId::new("split"),
                op: OperatorSpec::PdfEdit(PdfEditOptions::KeepPages(SplitOptions {
                    pages: "1".to_owned(),
                })),
                inputs: vec![artifact_ref("source")],
            },
            &[Artifact::pdf(pdf)],
        )
        .unwrap_err();

    assert_eq!(
        err,
        OxideError::ResourceLimitExceeded {
            limit: "max_output_bytes".to_owned()
        }
    );
}

#[test]
fn object_level_operator_emits_parsed_pdf_object() {
    // A migrated page operator returns a parsed object tree, not serialized
    // bytes, so a downstream operator can consume it without re-parsing.
    let pdf = include_bytes!("../../../tests/test.pdf");
    let runner = PdfOperatorRunner::default();

    let artifact = runner
        .run(
            &TaskSpec {
                id: TaskId::new("keep"),
                op: OperatorSpec::PdfEdit(PdfEditOptions::KeepPages(SplitOptions {
                    pages: "1".to_owned(),
                })),
                inputs: vec![artifact_ref("source")],
            },
            &[Artifact::pdf(pdf)],
        )
        .unwrap();

    assert!(matches!(artifact, Artifact::PdfObject(_)));

    // The object artifact feeds straight into another object-level operator.
    let chained = runner
        .run(
            &TaskSpec {
                id: TaskId::new("extract"),
                op: OperatorSpec::PdfEdit(PdfEditOptions::ExtractPages(PageSelectionOptions {
                    pages: "1".to_owned(),
                })),
                inputs: vec![artifact_ref("keep")],
            },
            &[artifact],
        )
        .unwrap();
    assert!(matches!(chained, Artifact::PdfObject(_)));
}

#[test]
fn pdf_operator_runner_emits_signature_verification_report() {
    let pdf = pdf_with_signature_dictionary(vec![0, 64, 192, 64], vec![0x30, 0x82]);
    let trust_anchors = write_test_trust_anchors("signature_report");
    let runner = PdfOperatorRunner::default();

    let artifact = runner
        .run(
            &TaskSpec {
                id: TaskId::new("verify"),
                op: OperatorSpec::PdfSign(PdfSignOptions::Verify(SignatureOptions {
                    mode: SignatureMode::Verify,
                    trust_anchors: Some(trust_anchors),
                })),
                inputs: vec![artifact_ref("source")],
            },
            &[Artifact::pdf(&pdf)],
        )
        .unwrap();

    let Artifact::Text(report_text) = artifact else {
        panic!("signature verification should emit a text JSON report");
    };
    let report: SignatureVerificationReport = serde_json::from_str(&report_text.text).unwrap();
    assert_eq!(report.trust_anchor_count, 1);
    assert_eq!(report.verdict, SignatureVerdict::Invalid);
    assert_eq!(report.signatures.len(), 1);
    assert_eq!(report.signatures[0].field_name.as_deref(), Some("Approval"));
    assert_eq!(
        report.signatures[0].subfilter.as_deref(),
        Some("adbe.pkcs7.detached")
    );
    assert_eq!(
        report.signatures[0].byte_range.values,
        Some([0, 64, 192, 64])
    );
    assert!(report.signatures[0].byte_range.in_bounds);
    assert!(report.signatures[0].byte_range.ordered_non_overlapping);
    assert_eq!(report.signatures[0].byte_range.gap_len, Some(128));
    assert_eq!(
        report.signatures[0].cms_status.status,
        SignatureCheckState::Failed
    );
    assert_eq!(
        report.signatures[0].revocation_status.status,
        SignatureCheckState::Indeterminate
    );
}

#[test]
fn pdf_operator_runner_emits_signature_list_report_without_trust_anchors() {
    let pdf = pdf_with_signature_dictionary(vec![0, 64, 192, 64], vec![0x30, 0x82]);
    let runner = PdfOperatorRunner::default();

    let artifact = runner
        .run(
            &TaskSpec {
                id: TaskId::new("list"),
                op: OperatorSpec::PdfSign(PdfSignOptions::List(SignatureOptions {
                    mode: SignatureMode::List,
                    trust_anchors: None,
                })),
                inputs: vec![artifact_ref("source")],
            },
            &[Artifact::pdf(&pdf)],
        )
        .unwrap();

    let Artifact::Text(report_text) = artifact else {
        panic!("signature list should emit a text JSON report");
    };
    let report: SignatureListReport = serde_json::from_str(&report_text.text).unwrap();
    assert_eq!(report.signatures.len(), 1);
    assert_eq!(report.signatures[0].field_name.as_deref(), Some("Approval"));
    assert_eq!(
        report.signatures[0].subfilter.as_deref(),
        Some("adbe.pkcs7.detached")
    );
    assert_eq!(
        report.signatures[0].byte_range.values,
        Some([0, 64, 192, 64])
    );
    assert!(report.diagnostics.is_empty());
}

#[test]
fn pdf_operator_runner_handles_extract_text_tasks() {
    let pdf = include_bytes!("../../../tests/test.pdf");
    let runner = PdfOperatorRunner::default();

    let extracted = runner
        .run(
            &TaskSpec {
                id: TaskId::new("extract"),
                op: OperatorSpec::PdfInspect(PdfInspectOptions::ExtractText(
                    ExtractTextOptions::default(),
                )),
                inputs: vec![artifact_ref("source")],
            },
            &[Artifact::pdf(pdf)],
        )
        .unwrap();

    let Artifact::Text(text) = extracted else {
        panic!("expected text artifact");
    };
    assert!(!text.text.trim().is_empty());
}

#[test]
fn execute_workflow_enforces_timeout() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.bin" }],
              "tasks": [
                {
                  "id": "slow",
                  "op": { "pdf_edit": { "merge": {} } },
                  "inputs": ["source"]
                }
              ],
              "outputs": [{ "id": "final", "from": "slow", "path": "out.bin" }],
              "limits": { "timeout_ms": 1 }
            }
            "#,
    );
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("source"), Artifact::bytes(b"input"));
    let runner = SlowRunner;

    let err = execute_workflow(&workflow, store, &runner).unwrap_err();

    assert_eq!(
        err,
        OxideError::ResourceLimitExceeded {
            limit: "timeout_ms".to_owned()
        }
    );
}

#[test]
fn independent_tasks_in_a_layer_run_in_parallel() {
    // Eight independent tasks each sleep 50ms. Run serially that is 400ms; in
    // parallel it should finish in well under that. Use a generous bound to stay
    // robust on busy CI while still proving concurrency.
    let tasks = (0..8)
        .map(|i| {
            format!(
                r#"{{ "id": "t{i}", "op": {{ "pdf_edit": {{ "merge": {{}} }} }}, "inputs": ["source"] }}"#
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    let outputs = (0..8)
        .map(|i| format!(r#"{{ "id": "o{i}", "from": "t{i}", "path": "out{i}.bin" }}"#))
        .collect::<Vec<_>>()
        .join(",");
    let workflow = workflow_from_json(&format!(
        r#"
            {{
              "version": 1,
              "inputs": [{{ "id": "source", "path": "input.bin" }}],
              "tasks": [{tasks}],
              "outputs": [{outputs}]
            }}
            "#,
    ));
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("source"), Artifact::bytes(b"input"));

    struct SleepRunner;
    impl OperatorRunner for SleepRunner {
        fn run(&self, task: &TaskSpec, _inputs: &[Artifact]) -> Result<Artifact, OxideError> {
            std::thread::sleep(std::time::Duration::from_millis(50));
            Ok(Artifact::bytes(task.id.as_str().as_bytes()))
        }
    }

    let started = std::time::Instant::now();
    let result = execute_workflow(&workflow, store, &SleepRunner).unwrap();
    let elapsed = started.elapsed();

    assert_eq!(result.plan.task_order.len(), 8);
    // Serial would be ~400ms; require comfortably below that.
    assert!(
        elapsed < std::time::Duration::from_millis(300),
        "expected parallel execution, took {elapsed:?}"
    );
}

#[test]
fn execute_workflow_enforces_total_input_size_limit() {
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [
                { "id": "first", "path": "a.bin" },
                { "id": "second", "path": "b.bin" }
              ],
              "tasks": [],
              "outputs": [{ "id": "final", "from": "first", "path": "out.bin" }],
              "limits": { "max_total_input_bytes": 9 }
            }
            "#,
    );
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("first"), Artifact::bytes(b"12345"));
    store.insert(artifact_ref("second"), Artifact::bytes(b"67890"));
    let runner = RecordingRunner::default();

    let err = execute_workflow(&workflow, store, &runner).unwrap_err();

    assert_eq!(
        err,
        OxideError::ResourceLimitExceeded {
            limit: "max_total_input_bytes".to_owned()
        }
    );
    assert!(runner.executed().is_empty());
}

#[test]
fn artifact_bytes_clone_is_zero_copy() {
    let payload = vec![7u8; 4096];
    let original = ArtifactBytes::from(payload);
    let cloned = original.clone();

    // Cloning an ArtifactBytes must share the same backing allocation rather
    // than copying the bytes, so the two views point at the same address.
    assert_eq!(original.as_ptr(), cloned.as_ptr());
    assert_eq!(original.as_slice(), cloned.as_slice());
}

#[test]
fn from_arc_is_zero_copy() {
    let arc: std::sync::Arc<[u8]> = std::sync::Arc::from(vec![5u8; 4096].into_boxed_slice());
    let arc_ptr = arc.as_ptr();

    let bytes = ArtifactBytes::from_arc(arc);

    // Adopting an existing Arc must not reallocate or copy; the payload points
    // at the same address the Arc already owned.
    assert_eq!(bytes.as_ptr(), arc_ptr);
    assert!(!bytes.is_spilled());
    assert_eq!(bytes.len(), 4096);
}

#[test]
fn from_arc_clone_shares_buffer() {
    let arc: std::sync::Arc<[u8]> = std::sync::Arc::from(vec![1u8; 1024].into_boxed_slice());
    let bytes = ArtifactBytes::from(arc);
    let cloned = bytes.clone();

    assert_eq!(bytes.as_ptr(), cloned.as_ptr());
    assert_eq!(bytes.as_slice(), cloned.as_slice());
}

#[test]
fn artifact_clone_shares_pdf_payload() {
    let artifact = Artifact::pdf(vec![1u8; 1024]);
    let cloned = artifact.clone();

    let (Artifact::Pdf(original), Artifact::Pdf(copy)) = (&artifact, &cloned) else {
        panic!("expected PDF artifacts");
    };
    assert_eq!(original.bytes.as_ptr(), copy.bytes.as_ptr());
}

#[test]
fn small_artifact_stays_inline() {
    let bytes = ArtifactBytes::from(vec![9u8; 1024]);
    assert!(!bytes.is_spilled());
    assert_eq!(bytes.len(), 1024);
}

#[test]
fn large_artifact_spills_to_disk_and_reads_back() {
    // Exceed the 64 MiB spill threshold by a little; the payload must move to a
    // memory-mapped temp file yet still expose identical bytes.
    let size = 64 * 1024 * 1024 + 4096;
    let mut payload = vec![0u8; size];
    payload[0] = 1;
    payload[size - 1] = 2;
    let bytes = ArtifactBytes::from(payload);

    assert!(bytes.is_spilled());
    assert_eq!(bytes.len(), size);
    assert_eq!(bytes.as_slice()[0], 1);
    assert_eq!(bytes.as_slice()[size - 1], 2);

    // Cloning a spilled payload shares the mapping; both views read the same data.
    let cloned = bytes.clone();
    assert_eq!(cloned.as_slice(), bytes.as_slice());
}

#[test]
fn spilled_payload_roundtrip_is_byte_exact() {
    // A spilled payload must read back byte-for-byte, not just at the endpoints.
    // Fill with a position-dependent pattern so any truncation, offset, or
    // partial write would surface.
    let size = 64 * 1024 * 1024 + 7919;
    let mut payload = vec![0u8; size];
    for (index, byte) in payload.iter_mut().enumerate() {
        *byte = (index % 251) as u8;
    }
    let bytes = ArtifactBytes::from(payload.clone());

    assert!(bytes.is_spilled());
    assert_eq!(bytes.as_slice(), payload.as_slice());
}

#[test]
fn workflow_spill_threshold_forces_small_output_to_spill() {
    // A zero spill threshold means "spill every non-empty payload". The task
    // emits a tiny output that would normally stay inline; the workflow's
    // threshold must push it to a memory-mapped temp file.
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.bin" }],
              "tasks": [
                {
                  "id": "echo",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["source"]
                }
              ],
              "outputs": [{ "id": "final", "from": "echo", "path": "out.bin" }],
              "limits": { "spill_threshold_bytes": 0 }
            }
            "#,
    );
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("source"), Artifact::bytes(b"input"));

    struct EchoRunner;
    impl OperatorRunner for EchoRunner {
        fn run(&self, _task: &TaskSpec, _inputs: &[Artifact]) -> Result<Artifact, OxideError> {
            Ok(Artifact::pdf(b"tiny"))
        }
    }

    let result = execute_workflow(&workflow, store, &EchoRunner).unwrap();
    let Some(Artifact::Pdf(pdf)) = result.store.get(&artifact_ref("echo")) else {
        panic!("expected a PDF artifact");
    };
    assert!(pdf.bytes.is_spilled());
}

#[test]
fn workflow_spill_threshold_keeps_large_output_inline_when_high() {
    // A high threshold keeps an otherwise-spillable payload inline.
    let workflow = workflow_from_json(
        r#"
            {
              "version": 1,
              "inputs": [{ "id": "source", "path": "input.bin" }],
              "tasks": [
                {
                  "id": "echo",
                  "op": { "pdf_edit": { "rotate_pages": { "pages": "1", "degrees": 90 } } },
                  "inputs": ["source"]
                }
              ],
              "outputs": [{ "id": "final", "from": "echo", "path": "out.bin" }],
              "limits": { "spill_threshold_bytes": 1073741824 }
            }
            "#,
    );
    let mut store = ArtifactStore::new();
    store.insert(artifact_ref("source"), Artifact::bytes(b"input"));

    struct BigRunner;
    impl OperatorRunner for BigRunner {
        fn run(&self, _task: &TaskSpec, _inputs: &[Artifact]) -> Result<Artifact, OxideError> {
            // Larger than the default 64 MiB threshold, smaller than the 1 GiB
            // workflow threshold, so only the workflow threshold decides.
            Ok(Artifact::pdf(vec![0u8; 64 * 1024 * 1024 + 4096]))
        }
    }

    let result = execute_workflow(&workflow, store, &BigRunner).unwrap();
    let Some(Artifact::Pdf(pdf)) = result.store.get(&artifact_ref("echo")) else {
        panic!("expected a PDF artifact");
    };
    assert!(!pdf.bytes.is_spilled());
}
