//! Integration tests for the `workflow` public API surface.
//!
//! Generated by splitting the former monolithic `src/tests.rs`. These exercise
//! only the crate's public API; private-API behaviour is unit-tested in `src/`.

mod common;
include!("workflow/workflow_schema_version_starts_at_one.rs");
include!("workflow/parses_document_interaction_workflow_operator_schema.rs");
include!("workflow/dag_workflow_topologically_sorts_before_execution.rs");
include!("workflow/parses_overlay_image_color_operator_schema.rs");
include!("workflow/parses_security_operator_schema.rs");
include!("workflow/pdf_operator_runner_emits_signature_verification_report.rs");
include!("workflow/artifact_bytes_clone_is_zero_copy.rs");
include!("workflow/workflow_spill_threshold_forces_small_output_to_spill.rs");
